name: Test-App

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout scylla
      with:
        repository: scylladb/scylla
        path: scylla
        submodules: recursive

    - uses: actions/checkout@v2
      name: Checkout scylla-dtest
      with:
        repository: scylladb/scylla-dtest
        token: ${{ secrets.GB_TEMP }}
        path: scylla-dtest

    - name: Build (release mode)
      working-directory: ./scylla
      run: |
        ./tools/toolchain/dbuild ./configure.py --mode=release
        ./tools/toolchain/dbuild ninja release-build

    - name: Unit-Tests (release mode)
      working-directory: ./scylla
      run: |
        ./tools/toolchain/dbuild ninja release-test

    - name: Smoke-Tests
      working-directory: scylla-dtest
      run: |
        CASSANDRA_DIR=../scylla ./scripts/run_test.sh -m dtest_smoke
